name: initial trigger action

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: init-brand-monitor # set this to your application's name, it has to be unique
  AZURE_GROUP_NAME: init-brand-monitor_group
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub action'
      uses: actions/checkout@v2

    - name: Install with RustUp
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install musl
      run: sudo apt-get install -y --no-install-recommends musl-tools

    - name: Add Target
      shell: bash
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build release
      shell: bash
      run: |
       cargo build --release --manifest-path=init_trigger/Cargo.toml --target=x86_64-unknown-linux-musl
       cp init_trigger/target/x86_64-unknown-linux-musl/release/handler .
    - name: Copy handler to parent directory
      shell: bash
      run: cp init_trigger/target/x86_64-unknown-linux-musl/release/handler .

    - name: Install Azure Core Tools
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-4
          
    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        respect-funcignore: true
